services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  diploma-api:
    build:
      context: ./api-certificado
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=prog_diplomas
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - redis
      - mysql
      - rabbitmq
    ports:
      - "3000:3000"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=prog_diplomas
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    image: puppeteer/puppeteer-latest
    depends_on:
      - redis
      - mysql
      - rabbitmq
    volumes:
      - ./storage:/usr/src/app/storage
    command: ["node", "index.js", "--no-sandbox", "--disable-setuid-sandbox"]

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prog_diplomas
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123

volumes:
  mysqldata:
  rabbitmq_data:
  templates:
